build: off
version: '{build}'
environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'
platform:
  - x86
  - x64
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
after_test:
  - npm run bench
  - npm run coverage
