sudo: false
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
  - '6'
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - node --version
  - npm --version
  - npm test
after_success:
  - npm run bench
  - npm run coverage
