name: test-windows

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: windows-latest
    name: AVA & TSD & Benchmark & Codecov
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install lib dependencies
        run: |
          npm install --only=prod
          npm list --prod --depth=0
      - name: Install dev dependencies
        run: |
          npm install --only=dev
          npm list --dev --depth=0
      - name: Run tests
        if: ${{ matrix.node <= 6 }}
        run: npm run test
      - name: Run tests
        if: ${{ !(matrix.node <= 6) }}
        run: npm run test:windows
      #- name: Run type checking
      #  run: npm run types
      - name: Run benchmark
        run: |
          npm run bench
      - name: Upload coverage to Codecov
        if: ${{ matrix.node <= 6 }}
        uses: codecov/codecov-action@v2
